version: '3.8'

services:

  backend:
    image: ghcr.io/misternegative21/vihang:sha-6db3c69
    container_name: vihang_backend
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: vihang_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
  caddy_data:
  caddy_config:
